### ISSUE TITLE
XY-LPWM

### ISSUE THREAD

**Issue by Igor26974** [achilikin/N76E003-SDCC-BSP#1]
I found a link to your repository for XY-LPWM on the Internet.
I wanted to make an indicator for myself based on PWM XY-LPWM.
I ordered the boards on Aliexpress, but when I received them, it turned out that they had another controller with a worn-out name (in the SOP-16 case).
image
![image](https://github.com/achilikin/N76E003-SDCC-BSP/assets/145862740/6187d96b-e621-4b3e-b5d2-0b00f38c87ab)

Do you happen to know what controller this is???

**Comment by achilikin** [comment]
Boards I used for prototyping had XY-LPWM label printed on them, similar to this [one](https://sklep-elektronika.com/environment/cache/images/515_515_productGfx_1371/generator-sygnalu-pwm-wyswietlacz-lcd-lpwm-xy.webp).
The board you have uses some sort of PIC microcontroller or PIC analog.

**Comment by achilikin** [comment]
Added pictures of the boards used for prototyping
